//! Pure fractional position key generator (§1.5).
//!
//! # Alphabet
//! Base-62, ASCII-ordered: `0-9A-Za-z` (characters 48-57, 65-90, 97-122 in ASCII order).
//! Because the alphabet characters are in strictly increasing ASCII byte order, standard
//! lexicographic string comparison (byte-by-byte) yields the same ordering as the
//! alphabet-position ordering.  No custom comparator is needed.
//!
//! # Contract
//! `between(a, b)` returns a key `m` such that:
//! - `a.is_some()` → `*a < m` (lexicographically)
//! - `b.is_some()` → `m < *b` (lexicographically)
//! - `a = None` means open lower bound (−∞).
//! - `b = None` means open upper bound (+∞).
//!
//! # Properties guaranteed by this module
//! - `between(None, None)` → a non-empty key in the middle of the alphabet.
//! - `between(a, None)` → strictly after `a` (appends one character).
//! - `between(None, b)` → strictly before `b` (decrements the last non-minimum character).
//! - `between(a, b)` where `a < b` → strictly between them; never a collision.
//! - Deterministic: same inputs always yield the same output.
//! - A sequence of N midpoint insertions between the same two bounds never collides and
//!   grows key length by at most one character per halving.
//!
//! # Known limitation
//! `between(None, "0")` (or any key whose every character is `'0'`) cannot return a valid
//! non-empty key, because `"0"` is the lexicographic minimum of any single-character key.
//! This case never arises in normal use because the rank system never generates `"0"` as a
//! key (all generated keys start from the mid-alphabet `"V"` and never append `'0'`).

/// The base-62 alphabet in strict ASCII order: 0-9 A-Z a-z.
const ALPHABET: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
/// Number of symbols in the alphabet.
const BASE: usize = 62;
/// Index of 'V' (ASCII 86) — the approximate midpoint of the alphabet (index 31 of 62).
const MID_IDX: usize = 31;

/// Returns the position (0-based) of `c` in ALPHABET.
///
/// # Panics
/// Panics if `c` is not in the alphabet.  All keys produced by this module are
/// guaranteed to only contain valid alphabet characters.
fn idx_of(c: u8) -> usize {
    ALPHABET.iter().position(|&b| b == c).unwrap_or_else(|| {
        panic!(
            "order::between — character {:?} is not in the base-62 alphabet",
            c as char
        )
    })
}

/// Returns a rank key strictly between `a` and `b`.
///
/// `None` on either side means an open bound:
/// - `a = None` → lower open bound (key may be anything below `b`).
/// - `b = None` → upper open bound (key may be anything above `a`).
pub fn between(a: Option<&str>, b: Option<&str>) -> String {
    match (a, b) {
        // No neighbors: return the mid-alphabet key.
        (None, None) => String::from_utf8(vec![ALPHABET[MID_IDX]]).unwrap(),

        // Only upper bound: append MID to go strictly after `a`.
        (Some(a), None) => {
            let mut out = a.as_bytes().to_vec();
            out.push(ALPHABET[MID_IDX]);
            String::from_utf8(out).unwrap()
        }

        // Only lower bound: step just before `b`.
        (None, Some(b)) => step_before(b),

        // Both bounds: compute the lexicographic midpoint.
        (Some(a), Some(b)) => midpoint_str(a, b),
    }
}

/// Returns a string strictly less than `b` by decrementing the last character
/// that is not at the alphabet minimum (`'0'`).
///
/// Examples:
/// - `"V"` → `"U"`
/// - `"VV"` → `"VU"`
/// - `"0V"` → `"0U"`
/// - `"1"` → `"0"`
/// - `"V0"` → `"U"` (trailing zeros absorbed by decrementing earlier char)
///
/// Returns an empty string for the degenerate all-`'0'` case (should never
/// arise from keys generated by this module).
fn step_before(b: &str) -> String {
    let bytes = b.as_bytes();
    if bytes.is_empty() {
        return String::new();
    }
    // Scan right-to-left to find the last character with index > 0.
    for i in (0..bytes.len()).rev() {
        let cur = idx_of(bytes[i]);
        if cur > 0 {
            // Decrement this character; everything after it is dropped.
            let mut result = bytes[..=i].to_vec();
            result[i] = ALPHABET[cur - 1];
            return String::from_utf8(result).unwrap();
        }
        // cur == 0 ('0'): this position is at the minimum; keep going left.
    }
    // All characters are '0' — no valid predecessor.
    String::new()
}

/// Returns a string strictly between `a` and `b`, given that `a < b`
/// lexicographically.
///
/// Algorithm: scan digits left-to-right.
/// - Equal digits: emit the digit and continue.
/// - Adjacent digits (`b_digit = a_digit + 1`): emit `a_digit`, copy the
///   rest of `a`, then append `MID_IDX` to land strictly above `a` and
///   strictly below `b` (since `b`'s next level is the `b_digit` branch).
/// - Gap of ≥ 2: emit the arithmetic midpoint and return.
///
/// When `a` is exhausted its digit is treated as 0 (minimum); when `b` is
/// exhausted its digit is treated as `BASE` (one past the maximum), ensuring
/// the algorithm terminates.
fn midpoint_str(a: &str, b: &str) -> String {
    debug_assert!(
        a < b,
        "order::midpoint_str requires a < b, but got a={:?} b={:?}",
        a,
        b
    );
    let a_bytes = a.as_bytes();
    let b_bytes = b.as_bytes();
    // + 1 to handle the case where both strings are exhausted at the same level.
    let max_len = a_bytes.len().max(b_bytes.len()) + 1;
    let mut result: Vec<u8> = Vec::with_capacity(max_len);

    for i in 0..max_len {
        let da: usize = if i < a_bytes.len() {
            idx_of(a_bytes[i])
        } else {
            0
        };
        let db: usize = if i < b_bytes.len() {
            idx_of(b_bytes[i])
        } else {
            BASE
        };

        if db == da {
            // Same digit at this level — emit it and continue.
            result.push(ALPHABET[da]);
        } else if db == da + 1 {
            // Adjacent digits — emit a's digit, copy a's tail, append MID.
            result.push(ALPHABET[da]);
            if i + 1 < a_bytes.len() {
                result.extend_from_slice(&a_bytes[i + 1..]);
            }
            result.push(ALPHABET[MID_IDX]);
            return String::from_utf8(result).unwrap();
        } else if db > da + 1 {
            // Gap of ≥ 2 — pick the arithmetic midpoint and return.
            result.push(ALPHABET[da + (db - da) / 2]);
            return String::from_utf8(result).unwrap();
        } else {
            // db < da: only possible if the caller violated the a < b precondition.
            panic!(
                "order::midpoint_str — a is not less than b at position {} \
                 (a={:?}, b={:?})",
                i, a, b
            );
        }
    }

    // Safety net: should be unreachable because `db - da >= 1` must trigger
    // before we exhaust `max_len` for any valid `a < b` pair.
    format!("{}{}", a, char::from(ALPHABET[MID_IDX]))
}

// ──────────────────────────────────────────────────────────────────────────────
// Tests — VG-P2 / VG-P9 rank invariants
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Core invariants ───────────────────────────────────────────

    /// `between(None, None)` returns a non-empty key.
    #[test]
    fn between_no_bounds_is_nonempty() {
        let k = between(None, None);
        assert!(!k.is_empty(), "between(None, None) must be non-empty");
    }

    /// `a < between(a, b) < b` for typical generated keys.
    #[test]
    fn between_both_bounds_is_strictly_in_range() {
        let a = "V";
        let b = "z";
        let m = between(Some(a), Some(b));
        assert!(a < m.as_str(), "between must be > a");
        assert!(m.as_str() < b, "between must be < b");
    }

    /// `between(None, b) < b` for a typical key.
    #[test]
    fn between_lower_open_is_less_than_b() {
        let b = "V";
        let m = between(None, Some(b));
        assert!(
            m.as_str() < b,
            "between(None, {:?}) = {:?} must be < b",
            b,
            m
        );
    }

    /// `a < between(a, None)` for a typical key.
    #[test]
    fn between_upper_open_is_greater_than_a() {
        let a = "V";
        let m = between(Some(a), None);
        assert!(
            a < m.as_str(),
            "between({:?}, None) = {:?} must be > a",
            a,
            m
        );
    }

    /// Determinism: calling `between` twice with the same inputs returns identical strings.
    #[test]
    fn between_is_deterministic() {
        let a = "MN";
        let b = "VV";
        assert_eq!(between(Some(a), Some(b)), between(Some(a), Some(b)));
        assert_eq!(between(None, Some(b)), between(None, Some(b)));
        assert_eq!(between(Some(a), None), between(Some(a), None));
    }

    /// A sequence of repeated `between(prev, upper)` insertions stays ordered and unique.
    #[test]
    fn repeated_insertions_between_bounds_stay_ordered() {
        let upper = "z";
        let mut keys: Vec<String> = Vec::new();
        let mut prev: Option<String> = None;

        for _ in 0..20 {
            let k = between(prev.as_deref(), Some(upper));
            if let Some(ref p) = prev {
                assert!(p.as_str() < k.as_str(), "new key must be > prev key");
            }
            assert!(k.as_str() < upper, "new key must be < upper bound");
            prev = Some(k.clone());
            keys.push(k);
        }

        // No collisions.
        let unique: std::collections::HashSet<&str> = keys.iter().map(String::as_str).collect();
        assert_eq!(unique.len(), keys.len(), "all keys must be distinct");
    }

    /// A sequence of `between(a, b)` midpoint insertions between the same pair keeps order.
    #[test]
    fn midpoint_insertions_between_pair_stay_ordered() {
        let mut lo = "V".to_string();
        let hi = "VV".to_string();

        for _ in 0..15 {
            let m = between(Some(&lo), Some(&hi));
            assert!(
                lo.as_str() < m.as_str(),
                "midpoint {:?} must be > lo {:?}",
                m,
                lo
            );
            assert!(
                m.as_str() < hi.as_str(),
                "midpoint {:?} must be < hi {:?}",
                m,
                hi
            );
            // Use midpoint as new lo to repeatedly split the lower half.
            lo = m;
        }
    }

    /// A sequence of prepend-before-first insertions is ordered and stays < initial key.
    #[test]
    fn repeated_prepend_before_stays_ordered() {
        let mut upper = "V".to_string();
        let mut keys: Vec<String> = Vec::new();

        for _ in 0..10 {
            let k = between(None, Some(&upper));
            if !k.is_empty() {
                assert!(k.as_str() < upper.as_str(), "{:?} must be < {:?}", k, upper);
                keys.push(k.clone());
                upper = k;
            }
        }
        // Verify global ordering of the collected prefix-keys.
        for pair in keys.windows(2) {
            assert!(pair[1] < pair[0], "earlier insertions must sort higher");
        }
    }

    // ── Alphabet edge cases ───────────────────────────────────────

    /// Adjacent single-char keys: between("V", "W") must land strictly between them.
    #[test]
    fn between_adjacent_single_chars() {
        let m = between(Some("V"), Some("W"));
        assert!("V" < m.as_str(), "must be > V");
        assert!(m.as_str() < "W", "must be < W");
    }

    /// Long key sequences: between always picks a midpoint without overflow.
    #[test]
    fn between_long_adjacent_keys() {
        // Simulate the output of repeated between(a, None) calls.
        let mut key = between(None, None);
        for _ in 0..10 {
            key = between(Some(&key), None);
        }
        // Key must still be a valid non-empty ASCII string in the alphabet.
        assert!(!key.is_empty());
        for c in key.bytes() {
            assert!(
                ALPHABET.contains(&c),
                "character {:?} not in alphabet",
                c as char
            );
        }
    }

    /// `between("0", "1")` returns a key strictly between them.
    #[test]
    fn between_first_two_chars() {
        let m = between(Some("0"), Some("1"));
        assert!("0" < m.as_str());
        assert!(m.as_str() < "1");
    }

    /// `step_before` on a single non-minimum char returns the previous char.
    #[test]
    fn step_before_single_char() {
        assert_eq!(step_before("V"), "U");
        assert_eq!(step_before("1"), "0");
        assert_eq!(step_before("a"), "Z");
    }

    /// All characters in any generated key are members of ALPHABET.
    #[test]
    fn all_generated_chars_in_alphabet() {
        let cases = [
            between(None, None),
            between(Some("V"), None),
            between(None, Some("z")),
            between(Some("0"), Some("z")),
            between(Some("VUz"), Some("VV")),
        ];
        for k in &cases {
            for c in k.bytes() {
                assert!(
                    ALPHABET.contains(&c),
                    "key {:?} contains character {:?} not in alphabet",
                    k,
                    c as char
                );
            }
        }
    }
}
